- name: docker install
  hosts: all
  become: yes
  tasks:
    - name: packages install
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
    - name: add docker pgp key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
    - name: apt update
      apt:
        update_cache: yes
    - name: docker packages install
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: docker compose install
      get_url: url=https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64 sha256sum=cfb3439956216b1248308141f7193776fcf4b9c9b49cbbe2fb07885678e2bb8a dest=/usr/local/bin/docker-compose mode="u=rx,g=rx,o=rx"
    - name: add docker group
      group:
        name: docker
    - name: add docker group
      user:
        name: vagrant
        group: docker
    - name: docker restart
      service:
        name: docker
        state: restarted