- name: movie tools install
  hosts: all
  become: yes
  tasks:
    - name: youtube-dl install
      pip:
        name:
          - youtube-dl
    - name: ffmpeg install
      apt:
        name:
          - ffmpeg