- name: nodejs install
  hosts: all
  tasks:
    - name: nvm install check
      command: bash -lc "which nvm"
      register: nvm_install_check
      changed_when: false
      ignore_errors: yes
    - name: nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      when: nvm_install_check is failed
    - name: node install check
      command: bash -lc "which node"
      register: node_install_check
      changed_when: false
      ignore_errors: yes
    - name: node install
      command: bash -lc "nvm install --lts" && bash -lc "nvm use --lts"
      when: node_install_check is failed
    - name: yarn install check
      command: bash -lc "which yarn"
      register: yarn_install_check
      changed_when: false
      ignore_errors: yes
    - name: yarn install
      command: bash -lc "npm install -g yarn"
      when: yarn_install_check is failed